name: photos
description: ente photos application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.29+195

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  photo_manager: ^1.0.6
  provider: ^3.1.0
  sqflite: ^2.0.0+3
  sqflite_migration: ^0.3.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  dio: ^4.0.0
  image: ^3.0.2
  share: ^2.0.1
  photo_view: ^0.11.1
  visibility_detector: ^0.2.0
  event_bus: ^2.0.0
  sentry: ^5.0.0
  super_logging:
    path: thirdparty/super_logging
  archive: ^3.1.2
  flutter_email_sender: ^5.0.0
  like_button: ^2.0.2
  logging: ^0.11.4
  flutter_image_compress:
    path: thirdparty/flutter_image_compress
  flutter_typeahead: ^1.8.1
  fluttertoast: ^8.0.6
  video_player: ^2.0.0
  chewie: ^1.0.0
  cached_network_image: ^3.0.0
  animate_do: ^1.7.2
  flutter_cache_manager: ^3.0.1
  computer: ^1.0.2
  flutter_secure_storage: ^4.2.0
  uni_links: ^0.5.1
  crisp: ^0.1.3
  flutter_sodium: ^0.2.0
  pedantic: ^1.9.2
  page_transition: "^1.1.7+2"
  scrollable_positioned_list: ^0.1.10
  connectivity: ^3.0.3
  url_launcher: ^6.0.3
  fluttercontactpicker: ^4.4.0
  in_app_purchase:
    path: thirdparty/in_app_purchase
  expansion_card: ^0.1.0
  flutter_password_strength: ^0.1.6
  flutter_inappwebview: ^5.3.2
  background_fetch: ^0.7.2
  # flutter_inapp_purchase: ^3.0.1
  google_nav_bar: ^5.0.5
  package_info_plus: ^1.0.1
  local_auth: ^1.1.5
  flutter_windowmanager: ^0.0.2
  flutter_user_agent: ^1.2.2
  quiver: ^3.0.1
  move_to_background: ^1.0.2
  loading_animations: ^2.1.0
  dots_indicator: ^2.0.0
  flutter_local_notifications: ^5.0.0+4
  open_file: ^3.2.1
  email_validator: '^1.0.6'
  extended_image: ^4.1.0
  image_editor: ^1.0.0
  syncfusion_flutter_sliders: ^19.1.67-beta
  syncfusion_flutter_core: ^19.1.67

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "0.9.0"
  flutter_native_splash: ^1.1.8+4

flutter_icons:
  android: true
  image_path_android: "assets/android_icon.png"
  ios: true
  image_path_ios: "assets/ios_icon.png"

flutter_native_splash:
  color: "#000000"
  image: assets/ios_icon.png
  android_gravity: center
  ios_content_mode: center
  android_fullscreen: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
  fonts:
  - family: NunitoSans
    fonts:
      - asset: fonts/NunitoSans-Regular.ttf
      - asset: fonts/NunitoSans-Bold.ttf
  - family: Ubuntu
    fonts:
      - asset: fonts/Ubuntu-Regular.ttf
      - asset: fonts/Ubuntu-Light.ttf
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Medium.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
